config:
  target: 'https://converter.imrajeshkumar7492.dev'
  phases:
    - duration: 60
      arrivalRate: 5
      name: "Warm up"
    - duration: 120
      arrivalRate: 10
      name: "Sustained load"
    - duration: 60
      arrivalRate: 20
      name: "Peak load"
  defaults:
    headers:
      User-Agent: 'Artillery Load Test'

scenarios:
  - name: "Frontend page load"
    weight: 40
    flow:
      - get:
          url: "/"
      - think: 3
      - get:
          url: "/static/css/main.css"
      - get:
          url: "/static/js/main.js"

  - name: "API health check"
    weight: 30
    flow:
      - get:
          url: "/api/health"
          expect:
            - statusCode: 200

  - name: "File upload simulation"
    weight: 20
    flow:
      - post:
          url: "/api/upload"
          formData:
            files: "test-files/sample.txt"
          expect:
            - statusCode: 200
      - think: 2

  - name: "Get supported formats"
    weight: 10
    flow:
      - get:
          url: "/api/supported-formats/JPG"
          expect:
            - statusCode: 200
            - hasProperty: "supported_formats"